export const UPDATE_SCORE = 'UPDATE_SCORE';
export const DECREASE_HEALTH = 'DECREASE_HEALTH';
export const INCREASE_HEALTH = 'INCREASE_HEALTH';
export const INCREMENT_LEVEL = 'INCREMENT_LEVEL';
export const RESET_GAME = 'RESET_GAME';